package assignment3.problem1.process;

import java.util.Objects;
import java.util.UUID;

/**
 * AutomatedDocument provides file generated from template with unique name
 * @author kabraambika19
 */
public class AutomatedDocument {
  private String uniqueName;
  private String documentContent;

  /**
   * Constructor of AutomatedDocument
   * @param documentContent content of file which is autogenerated from template and CSV, String
   */
  public AutomatedDocument(String documentContent) {
    this.uniqueName = this.randomIDGenerator();
    this.documentContent = documentContent;
  }

  /**
   * Gets the document content
   * @return this.documentContent
   */
  public String getDocumentContent() {
    return this.documentContent;
  }

  /**
   * get unique name for document name
   * @return this.uniqueName;
   */
  public String getUniqueName() {
    return this.uniqueName;
  }

  /**
   * This helper method is used to generate unique name for document
   * @return String
   */
  private String randomIDGenerator() {
    return UUID.randomUUID().toString();
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj) {
      return true;
    }
    if (obj == null || getClass() != obj.getClass()) {
      return false;
    }
    AutomatedDocument document = (AutomatedDocument) obj;
    return Objects.equals(this.getDocumentContent(), document.getDocumentContent());
  }

  @Override
  public int hashCode() {
    return Objects.hash(this.getDocumentContent());
  }

  @Override
  public String toString() {
    return "AutomatedDocument{" +
        "uniqueName='" + this.getUniqueName() + '\'' +
        ", documentContent='" + this.getDocumentContent() + '\'' +
        '}';
  }
}
